name: agrorammers
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.19.0
  google_sign_in: ^4.0.1+1
  rflutter_alert: ^1.0.2
  fluttertoast: ^3.1.3
  http: ^0.12.0+4
  url_launcher: ^5.4.1
#  sqflite: ^1.2.0
#  percent_indicator: ^2.1.1
#  pie_chart: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/old_men/1.png
   - assets/old_men/2.png
   - assets/old_men/3.png
   - assets/old_men/4.png
   - assets/old_men/5.png
   - assets/old_men/6.png

   - assets/catalog_items/Kök.png
   - assets/catalog_items/Xiyar.png
   - assets/catalog_items/Sarımsaq.png
   - assets/catalog_items/Yemiş.png
   - assets/catalog_items/Soğan.png
   - assets/catalog_items/Pomidor.png

   - assets/catalog_diseases/Pomidor/Təpə çürüməsi.jpg
   - assets/catalog_diseases/Pomidor/Meyvənin çatlaması.jpg
   - assets/catalog_diseases/Pomidor/Qara bakterial ləkəlilik.jpg
   - assets/catalog_diseases/Pomidor/Bakterial xərçəng.jpg
   - assets/catalog_diseases/Pomidor/Alternarioz.jpg


   - assets/catalog_diseases/Xiyar/Xiyar mozaikası.jpg
   - assets/catalog_diseases/Xiyar/Qaraayaq.jpg
   - assets/catalog_diseases/Xiyar/Yalançı unlu şeh.jpg
   - assets/catalog_diseases/Xiyar/Unlu şeh.jpg
   - assets/catalog_diseases/Xiyar/Askoxitoz.jpg
   - assets/catalog_diseases/Xiyar/Antraknoz.jpg
   - assets/catalog_diseases/Xiyar/Alternarioz.jpg
   - assets/catalog_diseases/Xiyar/Qara kif.jpg
   - assets/catalog_diseases/Xiyar/Fuzarioz soluxma.jpg
   

   - assets/catalog_diseases/Soğan/Yalançı unlu şeh xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Boğaz çürüməsi xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Fuzarioz gövdə çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Ağ çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Pas xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Bakterioz xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Alabəzəklilik xəstəliyi.jpg
   - assets/catalog_diseases/Soğan/Soğanın sürmə xəstəliyi.jpg
   
   - assets/catalog_diseases/Sarımsaq/Yalançı unlu şeh xəstəliyi.jpg
   - assets/catalog_diseases/Sarımsaq/Boğaz çürüməsi xəstəliyi.jpg
   - assets/catalog_diseases/Sarımsaq/Fuzarioz gövdə çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Sarımsaq/Ağ çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Sarımsaq/Pas xəstəliyi.jpg
   - assets/catalog_diseases/Sarımsaq/Bakterioz xəstəliyi.jpg
   
   - assets/catalog_diseases/Yemiş/Unlu şeh.jpg
   - assets/catalog_diseases/Yemiş/Yalançı unlu şeh.jpg
   - assets/catalog_diseases/Yemiş/Fuzarioz soluxması.jpg
   - assets/catalog_diseases/Yemiş/Antraknoz və ya ballıca.jpg
   - assets/catalog_diseases/Yemiş/Kök çürümələri.jpg
   - assets/catalog_diseases/Yemiş/Askoxitoz.jpg
   - assets/catalog_diseases/Yemiş/Boz çürümə.jpg
   - assets/catalog_diseases/Yemiş/Ağ ləkəlilik.jpg
   - assets/catalog_diseases/Yemiş/Qabaqkimilərin mozaikası.jpg
   - assets/catalog_diseases/Yemiş/Künc ləkəlilik xəstəliyi.jpg


   - assets/catalog_diseases/Kök/Qara çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Ağ çürümə.jpg
   - assets/catalog_diseases/Kök/Boz çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Quru çürümə xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Rizoktonioz xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Unlu şeh xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Yalançı unlu şeh xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Qaraayaq xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Bakterioz xəstəliyi.jpg
   - assets/catalog_diseases/Kök/Bakterial yaş çürümə xəstəliyi.jpg



   - assets/ui_icons/add_user.png
   - assets/ui_icons/user.png
   - assets/ui_icons/fertilizer.png
   - assets/ui_icons/seeds.png


   - assets/insect_items/Kök.png
   - assets/insect_items/Xiyar.png
   - assets/insect_items/Sarımsaq.png
   - assets/insect_items/Yemiş.png
   - assets/insect_items/Soğan.png
   - assets/insect_items/Pomidor.png


   - assets/insects/Xiyar/Danadişi.jpg
   - assets/insects/Xiyar/Mənənələr.jpg
   - assets/insects/Xiyar/Xiyar milçəyi.jpg
   - assets/insects/Xiyar/Tor gənəsi.jpg
   - assets/insects/Xiyar/Ağqanadlılar.jpg

   - assets/insects/Pomidor/Danadişi.jpg
   - assets/insects/Pomidor/Mənənələr.jpg
   - assets/insects/Pomidor/Tripslər.jpg
   - assets/insects/Pomidor/Gənələr.jpg
   - assets/insects/Pomidor/Məftil qurdu.jpg


   - assets/insects/Soğan/Tütün tripsi.jpg
   - assets/insects/Soğan/Soğanın kök gənəsi.jpg
   - assets/insects/Soğan/Soğan milçəyi.jpg
   - assets/insects/Soğan/Soğan güvəsi.jpg
   - assets/insects/Soğan/Soğanın gövdə nematodu.jpg


   - assets/insects/Yemiş/Gəmirici sovka.jpg
   - assets/insects/Yemiş/Məftil qurdları.jpg
   - assets/insects/Yemiş/Tor gənəciyi.jpg
   - assets/insects/Yemiş/Bostan mənənəsi.jpg
   - assets/insects/Yemiş/Yemiş milçəyi.jpg

   - assets/insects/Kök/Yerkökü uzunburunu.jpg
   - assets/insects/Kök/Yerkökü milçəyi.jpg
   - assets/insects/Kök/Çətirçiçək güvəsi.jpg

   - assets/insects/Sarımsaq/Tütün tripsi.jpg
   - assets/insects/Sarımsaq/Soğan milçəyi.jpg
   - assets/insects/Sarımsaq/Soğan güvəsi.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
